"""empty message

Revision ID: e542529192ad
Revises: a269b7affd46
Create Date: 2021-07-11 19:51:56.295446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e542529192ad'
down_revision = 'a269b7affd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('notes', sa.Column('time', sa.Time(), nullable=True))
    op.drop_constraint('notes_user_id_fkey', 'notes', type_='foreignkey')
    op.drop_column('notes', 'date_time')
    op.drop_column('notes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('notes_user_id_fkey', 'notes', 'users', ['user_id'], ['id'])
    op.drop_column('notes', 'time')
    op.drop_column('notes', 'date')
    # ### end Alembic commands ###
